### ISSUE TITLE
Not able to withdraw funds from active plan

### ISSUE THREAD

**Issue by davidubanyi** [omadoyeabraham/springverse-api#101]
Active plans should be able to withdraw funds to the wallet with a penalty, however the calculation of the amount to be withdrawn and the penalty is using the `goal` field instead of the `balance` field of the contribution check if the user has that mich in their plan to withdraw.

For example my active plan has a `goal` of 5000 but I've funded the plan with 50000, if I want to withdraw from that active plan it uses the 5000 to calculate instead of checking if the amount I want to withdraw is less than the balance of 50000

**Comment by omadoyeabraham** [comment]
@davidubanyi 

This has been resolved.
