### ISSUE TITLE
Online Loan Application Logic and Functionality

### ISSUE THREAD

**Issue by victorraji** [omadoyeabraham/springverse-api#103]
The branch manager should receive the online loan applications and assign them to an admin staff of his branch as against the workflow of a pull of online applications that the admin staff would process. Due to this change, we need new fields and new mutations on online loan application object.

**New Fields**
application_status: pending, assigned, processed, rejected. Defaults to pending when the user creates the loan application
admin_staff_id: default is null, set by the branch manager in the mutation
application_note: default is null, set by the adminstaff as a string that details the action they've taken on that loan application
**New Mutation**
UpdateOnlineLoanApplicationStatus - admin_staff_id, application_note, loan_id!, 
idea is having one mutation to handle both branch admin actions and admin staff we could split it if you think that would be better.

**Comment by victorraji** [comment]
pls @omadoyeabraham  see to this issue.

cc @davidubanyi

**Comment by victorraji** [comment]
pls @omadoyeabraham see to this issue.

cc @davidubanyi

**Comment by omadoyeabraham** [comment]
done
