### ISSUE TITLE
Inability to REDEEM Completed Funds

### ISSUE THREAD

**Issue by victorraji** [omadoyeabraham/springverse-api#104]
The User can't redeem to wallet ,its returning an error that says completed funds can't be withdrawn.

![Screen Shot 2020-05-15 at 10 27 12 PM](https://user-images.githubusercontent.com/37908822/82097865-aa84a980-96fb-11ea-9126-62611532e2c0.png)

@omadoyeabraham

**Comment by omadoyeabraham** [comment]
@victorraji 

This has been fixed, it now checks if the user is trying to withdraw from a completed plan, and if the amount is less than the plan balance. If so it throws an error asking the user to redeem the contribution plan instead.

**Comment by victorraji** [comment]
@omadoyeabraham works preety much well now.  cc @davidubanyi
