### ISSUE TITLE
Loan default status nullable error

### ISSUE THREAD

**Issue by victorraji** [omadoyeabraham/springverse-api#105]
![Screen Shot 2020-05-26 at 2 11 31 PM](https://user-images.githubusercontent.com/37908822/82904961-216f3d00-9f5b-11ea-86b4-8b92d4b22aef.png)

It should return non-nullablle for loans that are defaulting

@omadoyeabraham 

cc @davidubanyi

**Comment by omadoyeabraham** [comment]
@victorraji This has been fixed
