### ISSUE TITLE
Next due payment logic and features

### ISSUE THREAD

**Issue by phosmobile** [omadoyeabraham/springverse-api#106]
Expectations:
1. The next_due_payment field on the loan details should update to the next 30 days after a user's loan has been disbursed
2. When a loan payment transaction is processed successfully for the loan, the next due payment is shifted to the 30 days after the payment has been made.
3. Next due payment date should not 30 days after the due date of the loan, therefore if the loan due date has reached the next due payment date should not update.
4. A text message should be sent to the user three days before the next due payment and on the next due payment date. The messaging service should check for loans with the next_due_payment of that day/or three days in the future and send text messages to the users based on this.

**Comment by davidubanyi** [comment]
@omadoyeabraham please try to work on the next_due_payment (date) so we can close this issue. Thanks
