### ISSUE TITLE
Next_due_amount field and logic

### ISSUE THREAD

**Issue by davidubanyi** [omadoyeabraham/springverse-api#107]
Having reviewed the loan details and tracking structure there is need to add a next_due_amount field on the loan object, either as a generated field with graphql helpers or as a field in the db, the features of the field are as follows
1. It displays the amount the user is expected to pay for when making their loan repayments, this amount is dynamic as we cannot ascertain whether the user paid it fully the previous time neither can we force them to pay the amount.
the formula to generate the next_due_amount is as follows:
`Variables needed 

- interest_rate 
- amount_disbursed 
- loan_tenure
 
These 4 above variables should be derived from the loan object at time of enquiry 

(new variable) base_amount = amount_disbursed/ loan_tenure
(new variable) reducing_balance = amount_disbursed + base_amount 
(new variable) cummulative_interest = 0 
(new variable) interest = interest_rate/100 

Forloop (i = 1, i <=loan_tenure, i++){ 
reducing_balance -= base_amount 
cummulative_interest += reducing_balance * interest 
} 
return (loan balance) = amount_disbursed + cummulative_interest

 `
if you have issues with the formula or something is not clear please call me so we can discuss it. it's pseudo code as you can see but I believe it is straightforward enough, with this we can always know how much the person is expected to pay the next time they're making a payment.
2. The text message for reminder about loan payment would also contain the next_due_amount.

**Comment by davidubanyi** [comment]
@omadoyeabraham updated the formula

**Comment by omadoyeabraham** [comment]
@davidubanyi This has been done. The loan model now has the `nextDueAmountField`
