### ISSUE TITLE
Ability to retrieve the owner of a transaction from the transaction itself

### ISSUE THREAD

**Issue by omadoyeabraham** [omadoyeabraham/springverse-api#122]
We need a way to determine the owner of a transaction from the transaction itself

**SOLUTION**
I've added the "owner" field to the data returned for transactions, and it's a union of the following types 

1. Wallet
2. Contribution Plan
3. Company Branch
4. Loan

This means that the owner of a transaction can be any of these 4 types (more can be added in future as necessary).

Below is a sample Graphql fragment to let you know we can get the owner from a transaction:

```
query {
  GetTransactionById(id: "b0f42087-0c1b-45b6-949a-a55ed962f148") {
    id
    owner {
      __typename
      
      ... on Loan {
        id
        loan_repayment_source
      }
      
      ... on Wallet {
        id
        wallet_balance
      }
      
      ... on ContributionPlan {
        id
        type
        goal
      }
      
      ... on CompanyBranch {
        id
        name
        location
      }
    }
  }
}
```

Please note the following:

1. Anywhere where you receive a transaction's data, you can now also query for the owner field.
2. Note the __typename field, it is compulsory and will help you know the type of the transaction's owner
3. The fragments inside ... on {transaction owner type} can be populated with any field that is peculiar to that type of transaction owner. I.e when it's ... on Loan, you can get all fields that pertain to a loan.
4. Be careful to query for only the essential fields from transaction owners so we don't create redundant and cyclical queries, e.g a case where you get a transaction whose owner is a loan, then the transactions for the owning loan and then get the transactions for that owning loan, before getting the owners for those transactions again.

@davidubanyi  @victorraji  @enwemasor1995

**Comment by victorraji** [comment]
@omadoyeabraham the current query returns nothing on the response because of an `heuristic fragment match`

![20200705_160206](https://user-images.githubusercontent.com/37908822/86535717-3df78100-beda-11ea-8e5a-a94dfa3b6e3a.jpg)


this is a snapshot of the getBranchTransactions query

**Comment by victorraji** [comment]
![IMG-20200705-WA0007](https://user-images.githubusercontent.com/37908822/86535818-ead1fe00-beda-11ea-8eec-05987c895520.jpeg)

it returns a 200 response but an empty data..
pls what could be the issue? @omadoyeabraham

**Comment by eenwemasor** [comment]
`![MicrosoftTeams-image](https://user-images.githubusercontent.com/16518011/86536169-6765dc00-bedd-11ea-9a98-712b2347ca5a.png)`

the contributionPlan interface on the GetBranchTransactions  query returns the above error but the rest works just fine


```
`const getBranchTransactions = "gql
  query GetBranchTransactions(
    $branch_id: ID!
    $transaction_status: TransactionStatus
    $page: Int!
  ) {
    GetBranchTransactions(
      branch_id: $branch_id
      transaction_status: $transaction_status
      page: $page
    ) {
      paginatorInfo {
        currentPage
        firstItem
        hasMorePages
        total
        currentPage
      }
      data {
        id
        transaction_date
        transaction_type
        transaction_amount
        transaction_medium
        transaction_purpose
        transaction_status
        created_at
        owner {
          __typename
          ... on Loan {
            user {
              ...MemberFragment
            }
            ...LoanDetail
          }
          ... on CompanyBranch {
            id
            name
            location
          }
          ... on Wallet {
            id
            user_id
            wallet_id
            user {
              ...MemberFragment
            }
          }
        }
      }
    }
  }
  ${MemberFragment.user}
  ${LoanFragment.loans}
";

// without the below code works fine but with it return the error above


// ... on ContributionPlan {
//   id
//   user_id
//   type
//   goal
//   name
//   duration
//   balance
//   start_date
//   payback_date
//   interest_rate
//   interest_rate
//   frequency
//   contribution_id
//   created_at
// }
`
```


Also the ContributionPlan returns user_id instead of a user object

**Comment by eenwemasor** [comment]
@omadoyeabraham  also please refresh the database so i can pending transactions

**Comment by victorraji** [comment]
> `![MicrosoftTeams-image](https://user-images.githubusercontent.com/16518011/86536169-6765dc00-bedd-11ea-9a98-712b2347ca5a.png)`
> 
> the contributionPlan interface on the GetBranchTransactions query returns the above error but the rest works just fine
> 
> ```
> `const getBranchTransactions = "gql
>   query GetBranchTransactions(
>     $branch_id: ID!
>     $transaction_status: TransactionStatus
>     $page: Int!
>   ) {
>     GetBranchTransactions(
>       branch_id: $branch_id
>       transaction_status: $transaction_status
>       page: $page
>     ) {
>       paginatorInfo {
>         currentPage
>         firstItem
>         hasMorePages
>         total
>         currentPage
>       }
>       data {
>         id
>         transaction_date
>         transaction_type
>         transaction_amount
>         transaction_medium
>         transaction_purpose
>         transaction_status
>         created_at
>         owner {
>           __typename
>           ... on Loan {
>             user {
>               ...MemberFragment
>             }
>             ...LoanDetail
>           }
>           ... on CompanyBranch {
>             id
>             name
>             location
>           }
>           ... on Wallet {
>             id
>             user_id
>             wallet_id
>             user {
>               ...MemberFragment
>             }
>           }
>         }
>       }
>     }
>   }
>   ${MemberFragment.user}
>   ${LoanFragment.loans}
> ";
> 
> // without the below code works fine but with it return the error above
> 
> 
> // ... on ContributionPlan {
> //   id
> //   user_id
> //   type
> //   goal
> //   name
> //   duration
> //   balance
> //   start_date
> //   payback_date
> //   interest_rate
> //   interest_rate
> //   frequency
> //   contribution_id
> //   created_at
> // }
> `
> ```
> 
> Also the ContributionPlan returns user_id instead of a user object

@enwemasor1995  has this been fixed?
issue where its suppose to return  the user object

**Comment by omadoyeabraham** [comment]
done
