### ISSUE TITLE
Filter BranchMembers by roles

### ISSUE THREAD

**Issue by victorraji** [omadoyeabraham/springverse-api#127]
Current Condition: The `getBranchCustomer` query currently returns *customers* alone.

Expectation: There should be a way to fetch branch members by role e.g customer/admin staff/branch manager etc.

simply put:- I want to be able to get all the admin-staffs from a particular branch.

@omadoyeabraham 
cc @davidubanyi

**Comment by omadoyeabraham** [comment]
@victorraji Use the `GetBranchAdmins` for this.
