### ISSUE TITLE
Password Reset Failure

### ISSUE THREAD

**Issue by victorraji** [omadoyeabraham/springverse-api#128]
Current Condition: The `forgotPassword` mutation returns the following error on the input of an active email.

![Screen Shot 2020-07-09 at 1 01 59 AM](https://user-images.githubusercontent.com/37908822/86982021-22150900-c180-11ea-8720-46180999f19c.png)

Expectation: An reset password email sent to the email that was input.

@omadoyeabraham 
cc @davidubanyi

**Comment by omadoyeabraham** [comment]
@victorraji 

Fixed Now.

It sends a link that looks like this:  https://upspringvest.com/reset_password/52c5394274dde82625c7577daa088018c16458f645abcc0882f2baed860c2a3e

You need to catch that route in the frontend code and use the token in the url with the `updateForgottenPassword` mutation to update the user's password
