### ISSUE TITLE
Adding Filters to some Specific Queries

### ISSUE THREAD

**Issue by victorraji** [omadoyeabraham/springverse-api#129]
**Current condition** : We fetch the generic form of a query to get data and we filter that data from the front-end. It fetches quite alright **but** the pagination affects the results flow and in turn has a bad effect the eventual output when being filtered from the frontend.

 Take For example,

If I want a  Branch's `defaultingLoans`, I fetch all `branchLoans` which first produces 10 data because of the paginator. And in this `first 10` there are no defaulting loans, so after the filtering from my frontend,it  returns 0 datum on the first page. Till I click the 2nd page or a page that has a defaulting loan.

It also affects the paginator info

**Expectation** : The following queries should have filters for the  subsequent respective field on the right

QUERY   :            `FIELD TO FILTER BY` (REASON)

GetbranchLoans: `loan_default_status` (for defaulting loans)

GetbranchLoanApplications:`isAssigned` (for Loan applications that have **not** been assigned)

GetBranchLoans:`loan_application_status`(for loan applications that have been approved)

GetbranchLoanApplications:`admin_staff_id`(for Loan applications that have been assigned to a particular adminstaff).

(**new**)
GetbranchContributions: `status`(**completed** and **active**) (for Active branch contributors)

@omadoyeabraham @davidubanyi

**Comment by omadoyeabraham** [comment]
@victorraji Done

**Comment by victorraji** [comment]
@omadoyeabraham  Okay seen. Thanks.

but you didn't add the `GetbranchContributionPlans`.

or is there a way I can fetch all Contribution_Plans from a branch?

**Comment by omadoyeabraham** [comment]
@victorraji Use the `GetBranchContributionPlans` query

**Comment by victorraji** [comment]
@omadoyeabraham the GetbranchLoanApplications filtering by is_assigned is not returning the right Boolean results,there seems to be an error. 

and btw to start with, you used  the field `is_assigned` in the filter  and `isAssigned` in the data results.

please see to it

**Comment by omadoyeabraham** [comment]
@victorraji 

1. Use the is assigned variables as given, the isAssigned field is a computed field and cannot use snake case
2. Expatiate on how it is not returning the right results

**Comment by victorraji** [comment]
okay
it doesn't filter at all .it returns true for all cases. i.e it doesn't return `false`  `is_assigned` loans

**Comment by omadoyeabraham** [comment]
@victorraji The is_assigned flag serves as a filter. If passed in, it only returns loan applications of that value (either true or false).
If it is not passed in, it doesn't filter the list of loan applications by the is_assignend field.

I'd advise that you log in as a user, create a loan application and then query for it, it should return isAssigned as false

**Comment by victorraji** [comment]
Okay thanks, I understand.
Trust me to have tried all those before relaying them here.
the issue is
it doesn't filter for `is_assigned`= false ,  it returns all loans that have `isAssigned` to be true

pictoral example of the response data when  I filter by `is-assigned` = `false` below

![Screen Shot 2020-07-13 at 12 06 54 PM](https://user-images.githubusercontent.com/37908822/87298461-25065580-c502-11ea-8770-8b218755616d.png)
(**It returns all true for is_assigned**)

Pictorial example of the response data when  I don't filter at all by fetching all

![Screen Shot 2020-07-13 at 12 07 37 PM](https://user-images.githubusercontent.com/37908822/87298685-7dd5ee00-c502-11ea-9e3f-eb8413b0a557.png)

it returns some false fields for isAssigned here

so the is_assigned filter isn't functioning well

**Comment by omadoyeabraham** [comment]
@victorraji 

It's been fixed.
