### ISSUE TITLE
Get Branch Statistics Query

### ISSUE THREAD

**Issue by victorraji** [omadoyeabraham/springverse-api#130]
Expectation: A Query that gets a branch's Statistics

### statistics
- BRANCH MEMBERS
- 
- LOAN APPLICATIONS
- 
- DEFAULTING LOANS
- 
- ACTIVE CONTRIBUTORS
- 
- TRANSACTIONS

@omadoyeabraham 

cc @davidubanyi

**Comment by omadoyeabraham** [comment]
@victorraji Done
