### ISSUE TITLE
Initiate Transaction Error

### ISSUE THREAD

**Issue by victorraji** [omadoyeabraham/springverse-api#133]
Current Condition: Creating a branch expense( i.e transaction_type:`BRANCH_EXPENSE` ) using the `InitiateTransaction` mutation gives drops this error.

![Screen Shot 2020-07-13 at 5 55 21 PM](https://user-images.githubusercontent.com/37908822/87342179-be555c00-c542-11ea-8661-d75b4ebb6901.png)

with the query below
![Screen Shot 2020-07-13 at 6 08 06 PM](https://user-images.githubusercontent.com/37908822/87342202-c7462d80-c542-11ea-86bd-68ae7518240d.png)

@omadoyeabraham 
CC @davidubanyi

**Comment by omadoyeabraham** [comment]
@victorraji  Done
