### ISSUE TITLE
Query GetbranchAdmins returning the wrong data

### ISSUE THREAD

**Issue by victorraji** [omadoyeabraham/springverse-api#134]
Current Condition:The GetBranchAdmins Query currntly returns all types of roles
i.e Branchmanager,accountmanger,branchAccountant,AdminStaff etc from a branch.

Expectation: The query should return just members with role `adminStaff` as they are the one's that loans are being assigned to.

or u can add a filter `role` to the current query which one can then select the `adminStaff`

Simply put : I want to be able to fetch all adminStaffs from a branch

@omadoyeabraham 
cc @davidubanyi

**Comment by omadoyeabraham** [comment]
@victorraji roles filter added you'll need to pass an array of the roles you want.
