### ISSUE TITLE
createAdminUser MUTATION ERROR

### ISSUE THREAD

**Issue by victorraji** [omadoyeabraham/springverse-api#135]
There is something wrong with the  mutation, pls check it out
it wasn't working when I tried it on apollo(It just kept on loading, no response)

sample input

```
  createAdminUser(
    input: 
    {
    first_name: "Victor",
    last_name: "Abraham",
    phone_number: "08023457766", 
    company_id: "be04b4ba-5d01-40f1-81b1-2f9d04eef164",
    branch_id: "d40db2d8-358f-4062-a25f-1cd50c826d01",
    roles: ADMIN_STAFF,
    email: "adminnew@gmail.com"
    }
)
}
```

_**Please I stand to be corrected**_  as regards the sample  mutation

@omadoyeabraham 
cc @davidubanyi

**Comment by omadoyeabraham** [comment]
Roles should be an array of roles, wrap it in []

**Comment by victorraji** [comment]
okay, I did this 

roles: [ADMIN_STAFF]

still wasn't going

@omadoyeabraham

**Comment by omadoyeabraham** [comment]
What are the return fields you're selecting from the response?

**Comment by victorraji** [comment]
just id and email

@omadoyeabraham

**Comment by omadoyeabraham** [comment]
@victorraji It works now. You'll have to create using other credentials, as I used the ones in your query to test
