### ISSUE TITLE
call to member function addDays() ERROR on Branch Loans Query

### ISSUE THREAD

**Issue by victorraji** [omadoyeabraham/springverse-api#137]
![Screen Shot 2020-07-20 at 12 53 38 PM](https://user-images.githubusercontent.com/37908822/87935112-59d95600-ca88-11ea-84c6-8f4858241099.png)

Error on fetching all branch loans by Loan status

same error on fetching all branch loans
I think it has to with branch loans that are active. if a branch doesn't have an active loan , it doesn't bring that error,

@omadoyeabraham 
Cc @davidubanyi

**Comment by victorraji** [comment]
@omadoyeabraham just calling your attention to this, thanks

**Comment by victorraji** [comment]
This is currently working now, probably because the db has been cleared or refreshed
The issue was active loans

sample of the query: 

```
query MyQuery {
  __typename
  GetBranchLoans(branch_id: "7a32e8ed-afa7-4d7b-b1fa-9c9f153410db", loan_condition_status: ACTIVE) {
    data {
      application_status
      default_amount
    }
  }
}
```

**Comment by victorraji** [comment]
@omadoyeabraham pls reopen this issue, its affecting loans that are active, `call to member function addDays(error) error on user loans.

cc @davidubanyi

**Comment by omadoyeabraham** [comment]
Fixed
