### ISSUE TITLE
edit Profile mutatation

### ISSUE THREAD

**Issue by victorraji** [omadoyeabraham/springverse-api#138]
Ther should be a new mutation that updates a user's current profile
on these fields

phone_number
    profile {
      account_name
      account_number
      address
      bank_account_name
      bank_account_number
      bank_name
      bvn
      marital_status
      next_of_kin
      occupation
      relationship_with_next_of_kin
    }

@omadoyeabraham 
cc @davidubanyi

**Comment by omadoyeabraham** [comment]
@victorraji The updateUserProfile mutation has been created
