### ISSUE TITLE
Error on funding plan from wallet balance

### ISSUE THREAD

**Issue by victorraji** [omadoyeabraham/springverse-api#139]
On an Adminstaff view, I got this error below when trying to fund a contribution.

![image](https://user-images.githubusercontent.com/37908822/88179184-6b0a9a00-cc23-11ea-9439-eb46094c8cc4.png)

pls check it out. thanks

@omadoyeabraham 

cc @davidubanyi

**Comment by omadoyeabraham** [comment]
@victorraji Done
