### ISSUE TITLE
Error on  GetBranchTransactions by transaction staTUS

### ISSUE THREAD

**Issue by victorraji** [omadoyeabraham/springverse-api#140]
Current cond: Filtering the GetBranchTransactions query by transaction_status field gives the below error

![image](https://user-images.githubusercontent.com/37908822/88180173-e1f46280-cc24-11ea-918b-b4242f872aa0.png)
@omadoyeabraham 

but getting  all the transactions without the filter  works just fine

cc @davidubanyi

**Comment by omadoyeabraham** [comment]
@victorraji Please include a sample of the query

**Comment by victorraji** [comment]
This also work now.
