### ISSUE TITLE
more ROLES on the createAdminUser Mutation

### ISSUE THREAD

**Issue by victorraji** [omadoyeabraham/springverse-api#141]
CURRENT CONDITION: The Admin User currently has three Roles on the mutation; admin_staff,adminAccountant, and adminManager

EXPECTATION: There should be more than three roles that can be created with the mutation namely
adminStaff,
adminAccountant,
adminManager,
BranchManager,
BranchAccountant

@omadoyeabraham 

cc @davidubanyi

**Comment by omadoyeabraham** [comment]
@victorraji Done
