### ISSUE TITLE
Update password not correctly mutating

### ISSUE THREAD

**Issue by victorraji** [omadoyeabraham/springverse-api#142]
The mutation works well and gives a success message

 but on entering the newly updated password on the platform, it shows _incorrect credentials_

I think they are not correctly updated 

**The Mutation**

```
  updateForgottenPassword(input: {
    email:"damisarv@gmail.com",
    token: "b7a2feea84af6ee3ba83f9baaeb084f31400d8d1ca914fe48e211fb56b33ce20",
    password: "password1", 
    password_confirmation: "password1"
  }) {
    message
    status
  }
}
```
**THE RESPONSE I GOT BELOW**
```
{
  "data": {
    "__typename": "Mutation",
    "updateForgottenPassword": {
      "message": "Your password has been reset!",
      "status": "PASSWORD_UPDATED",
      "__typename": "ForgotPasswordResponse"
    }
  }
}
```

PLS NOTE: It also wasn't registering the old password i.e the old password currently shows _incorrect credentials_ also

 @omadoyeabraham 
cc @davidubanyi

**Comment by omadoyeabraham** [comment]
@victorraji This is fixed now

**Comment by victorraji** [comment]
It's bringing a new error now even before I try to update the password.

**undefined index token error**

 when I click on the `send reset link` button.

snapshot below

![image](https://user-images.githubusercontent.com/37908822/89026422-99256380-d320-11ea-98d1-cc56b6e67b80.png)


@omadoyeabraham

**Comment by omadoyeabraham** [comment]
@victorraji This is resolved now
