### ISSUE TITLE
Needed GraphQL queries

### ISSUE THREAD

**Issue by omadoyeabraham** [omadoyeabraham/springverse-api#28]
- [x] Get client details by id
- [x] Get all clients in branch by branch id
- [x] Get transaction detail by transaction id
- [x] Get loan application details by application ID
- [x] Get loan applications by branch id
- [x] Get loans by branch id and loan status
- [x] Get loan details by client id
- [x] Get client’s transactions by client ID and type
- [x] Get Contribution plans by User ID
- [ ] Get members by branch and search query
- [ ] Get branch loan by application status
- [ ] Get clients transactions by branch id and type
- [ ] Get active contributors by branch id
- [ ] Get contributions by type and branch id
- [ ] Get Loan applications by User ID
- [ ] Get Transactions by Branch ID, add filter by transaction type

**Comment by davidubanyi** [comment]
- [ ] Change the default count/per page count for paginated queries to 10
