### ISSUE TITLE
Loan Bugs

### ISSUE THREAD

**Issue by davidubanyi** [omadoyeabraham/springverse-api#40]
- [x] **Create Loan should be created without explicitly setting the following,** 

- [x] loan_balance, 
- [x] next_due_payment, 
- [x] due_date, 
- [x] default_amount, 
- [x] disbursement_status, 
- [x] disbursement_date, 
- [x] amount_disbursed, 
- [x] application_status, 
- [x] loan_condition_status, 
- [x] loan_default_status, 
- [x] num_of_default_days.

- [x] A user can ONLY HAVE ONE loan on their account per time, NO USER should have multiple loans running concurrently.

- [x] Each loan should have an activity bar that records the events of different users on the loan

**Comment by omadoyeabraham** [comment]
Issues herein detailed have been resolved in https://github.com/omadoyeabraham/springverse-api/pull/45
