### ISSUE TITLE
Client Stats Query

### ISSUE THREAD

**Issue by davidubanyi** [omadoyeabraham/springverse-api#57]
**Description**:
This query should return various statistics about a client that is immediately accessible to be consumed on the frontend. It would be used for dashboard information and other quick and accessible information. Therefore it does not need to be paginated or searchable and should simply return the values of the query. Query should take the user_id and return the stats

**Stats for Client**
* Loan Stats
    * Loan Balance - if the user has an active loan this is the balance on the loan the user is supposed to pay
    * Next due payment
    * Next repayment date
    * Default charges - if the customer is defaulting this is the number of days of the default multiplied by the default amount
    * Total paid amount - how much has the user paid off
    * Active loan- this should return a true or false value that lets us know whether the user has an active loan or not. (From the loan condition status)
* Contributions Stats
    * Total contribution amount this is the sum of the balance of all the contribution plans the client has
    * Goal contribution sum - this is the sum of all the contribution balance with a type GOAL
    * Fixed contribution sum - this is the sum of all the contribution balance with a type FIXED
    * Locked contribution sum - this is the sum of all the contribution balance with a type LOCKED
    * Wallet Balance - this is the balance in the wallet available to be withdrawn by the client

**Comment by omadoyeabraham** [comment]
Closed in https://github.com/omadoyeabraham/springverse-api/pull/62
