### ISSUE TITLE
Get Contribution plans by User ID and type Query

### ISSUE THREAD

**Issue by davidubanyi** [omadoyeabraham/springverse-api#59]
This query should perform two functions
1. Return all contribution plans for the user if no type is set
2. Return all contribution plans for the user with the set type

**Comment by omadoyeabraham** [comment]
@Oluwablin 

This is the query that resolved the issue.

` """ Get user contribution plans by ID and contribution type """
    GetCustomerContributionPlans(
        customer_id: ID! @where(operator: "=", key: "user_id"),
        contribution_plan_type: ContributionType @where(operator: "=", key: "contribution_type")
    ): [ContributionPlan]!
    @all`
