### ISSUE TITLE
Cannot access user's wallet

### ISSUE THREAD

**Issue by davidubanyi** [omadoyeabraham/springverse-api#66]
The user query GetWalletById is expected to return the wallet details for the user instead it throws the following error when called, possibly because the table has not been dropped and recreated.

**Please treat asap**

"errors": [
    {
      "debugMessage": "SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation \"wallets\" does not exist\nLINE 1: select * from \"wallets\" where \"id\" = $1\n                      ^ (SQL: select * from \"wallets\" where \"id\" = dd8a3d55-df00-417d-983b-a502e1a14050)",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },

**Comment by Oluwablin** [comment]
![Screenshot (145)](https://user-images.githubusercontent.com/52815638/75962492-24aadd80-5ec4-11ea-808a-435ea3e4f54b.png)

@davidubanyi php artisan:migrate:fresh was run and attached to the PR opened. all done now when it is merge

**Comment by omadoyeabraham** [comment]
@davidubanyi @Oluwablin 

Closing this issue because it's not really an issue, and also please note that the GetWalletById query is redundant. It is better the get the wallet information from the query that returns a customers details.
