### ISSUE TITLE
User Signup Feature

### ISSUE THREAD

**Issue by davidubanyi** [omadoyeabraham/springverse-api#71]
Current Situation
-  A user can only be created by an admin
- The users created are sent a password to access their accounts which they can change to their own password

Expected
- Users should be able to sign up hence they can create their own passwords (sign up should only be for a CUSTOMER role and not for all types of users)
- Create a user mutation (CUSTOMER) should also take in a password, which can be set/unset, set if the user is signing up, unset if they are being created(its generated and sent to them) 
- Users(CUSTOMER) can still be created by the admin
- Users(CUSTOMER) that are created by admin should still have their passwords sent to them

**Comment by omadoyeabraham** [comment]
closed in https://github.com/omadoyeabraham/springverse-api/pull/72
