### ISSUE TITLE
Transfer funds from wallet to contribution plan, and withdraw funds from contribution plan to wallet

### ISSUE THREAD

**Issue by davidubanyi** [omadoyeabraham/springverse-api#84]
The wallet is the means for the user to engage transactions on the platform, there is a need for a mutation to withdraw funds from the wallet to into a contribution plan and vice versa. 

The suggested mutation should take the following parameters

amount, 
type (wallet_to_contribution/contribution_to_wallet)
 wallet id
contribution_id

Make sure checks are done to ensure the balance is consistent for the transaction to occur.

**Comment by omadoyeabraham** [comment]
Issue closed in https://github.com/omadoyeabraham/springverse-api/pull/93

Two GraphQL mutations were added to the Schema

- FundContributionPlanFromWallet
- WithdrawFromContributionPlanToWallet
