### ISSUE TITLE
Reset password mutation not working

### ISSUE THREAD

**Issue by davidubanyi** [omadoyeabraham/springverse-api#85]
When a user tries to reset a password by providing the email it returns the following error
<img width="940" alt="Screenshot 2020-03-23 at 07 46 13" src="https://user-images.githubusercontent.com/22851889/77289592-91064900-6cda-11ea-86b7-cbbb07e1f3a3.png">

please address

**Comment by omadoyeabraham** [comment]
@davidubanyi 

This has been resolved and sends an email.
The email has a link of this form 
`http://localhost:9595/password/reset?token=1d40656f3123c8b421faaeb66eebb108cc8e162549e9ca0475b7bc8a04eaf3bd`

The localhost:9595 is replaced with whatever the actual live URL is. You need to get the token from the URL and use it in the `updateForgottenPassword` mutation
