### ISSUE TITLE
Contribution Plan Logic

### ISSUE THREAD

**Issue by davidubanyi** [omadoyeabraham/springverse-api#90]
Description
This feature handles all the logic for the contribution, we handle the interest, withdrawal rules and the status of the contribution plan per time.

Contribution Status: A field that returns the current state of the contribution plan, a contribution plan can either be 
1. Inactive: this means the contribution plan has been created by the user but the balance is zero and no money has been added to it, or the start_date of the contribution is less than the current date.
2. Active: A contribution plan is active when the start_date is greater than the current date but less than the payback_date and when the contribution balance is greater than zero means there is money in the contribution.
3. Completed: A contribution plan is completed when the payback date has been reached and the previous state of the plan was active. 

Contribution Interest: A field created to calculate the interest on the contribution at the time of an inquiry, it calculates the interests by multiplying the interest accrued per day by the number of days the contribution has plan has been active for. It stops accruing interest on the payback_date of the contribution plan.

Withdrawal Rules: These are the rules applied to the contribution plan when a request for withdrawal is made. It checks the status of the plan and applies the rules where necessary. When a plan has been completed, it simply adds the interest accrued to the balance and that is the amount that is withdrawn to the wallet of the user.
For an active plan (a plan whose payback date has not been reached the following rules apply)
1. Locked plan - premature withdrawal is **not allowed** by the user, can only be initiated by the account manager (in case of death or unforeseen circumstances)
2. Fixed plan - 5 percent of the user's withdrawal amount, plus whatever interest they have gotten in the period can be withdrawn by the user.
3. Goal plan - 2 percent of the user's withdrawal amount on the plan plus the interest can be withdrawn by the user.

**Comment by omadoyeabraham** [comment]
@davidubanyi Please note that the field `contribution_amount` has been renamed to `contribution_goal` for clarity. You'll need to update your GraphQL queries accordingly.
