### ISSUE TITLE
User wallet not initialised for new user

### ISSUE THREAD

**Issue by davidubanyi** [omadoyeabraham/springverse-api#96]
Current Bug
When a new account is created the User.wallet field returns null, showing that no user wallet is present for the new user. A description of the error has been posted below

![image](https://user-images.githubusercontent.com/22851889/81575933-85143a80-939f-11ea-809c-d713a9c3deac.png)
Expectation
When a new user signs up, a wallet is created for the user with a balance of zero (0) naira. This wallet can then be mutated by adding funds via the payment gateway on the front end.

**Comment by omadoyeabraham** [comment]
@davidubanyi 
This issue has been fixed
