### ISSUE TITLE
New user loan statistics error

### ISSUE THREAD

**Issue by victorraji** [omadoyeabraham/springverse-api#97]
Current Condition: A new user doesn't have a loan but it tries to force the getLoanStatistics and returns an error.

![Screen Shot 2020-05-11 at 3 51 37 PM](https://user-images.githubusercontent.com/37908822/81577451-59924f80-93a1-11ea-82e8-a58a76741bf7.png)

Expectation: A new signed up user should be getting a response that describes "No applied Loan yet" on getting his statistics

**Comment by omadoyeabraham** [comment]
@victorraji 
This issue has been resolved
