### ISSUE TITLE
The Redeem Function on Completed Contribution Plans

### ISSUE THREAD

**Issue by victorraji** [omadoyeabraham/springverse-api#98]
Current Condition: No Redeem Option

Expectation: There should be endpoints for the redeem option

**Comment by omadoyeabraham** [comment]
@victorraji @davidubanyi 

We've decided to go with the following flow:
- The frontend redeem button sends a query to the existing WithdrawToWallet Mutation, but passes in the entire contribution plan balance as the amount

- Note that the redeem button MUST only be shown for contribution plans that have been completed.
