### ISSUE TITLE
New Signed-Up User Statistics Error

### ISSUE THREAD

**Issue by victorraji** [omadoyeabraham/springverse-api#99]
Current Condition: Stats are returning null values for a new user instead of zero

![image](https://user-images.githubusercontent.com/37908822/81698860-79d41400-945e-11ea-8c53-9ec1969b833d.png)

Expectation:New Users should have an initial value of zero not null

@omadoyeabraham

**Comment by omadoyeabraham** [comment]
@victorraji 
This issue has been resolved
